stages:
  - Build image
  - Push to Docker Hub
  - swarm deploy

variables:
  CONTAINER_IMAGE: wbarshop/milkyway_pulsar
  
before_script:
  - docker login -u "%REGISTRY_USER%" -p "%REGISTRY_PASSWORD%"
  
docker build:
  stage: Build image
  tags:
    - linux
  script:
    - docker info
    - docker pull %CONTAINER_IMAGE%:ci
    - docker build --cache-from %CONTAINER_IMAGE%:ci -t %CONTAINER_IMAGE%:ci -t %CONTAINER_IMAGE%:%CI_COMMIT_SHA% .

docker push:
  stage: Push to Docker Hub
  tags:
    - linux
  only:
    - master
  script:
    - docker push %CONTAINER_IMAGE%:ci
    
docker deploy:
  stage: swarm deploy
  tags:
    - windows
  script:
    - curl --request POST --form "token=%CI_JOB_TOKEN%" --form ref=master http://gitlab/api/v4/projects/3/trigger/pipeline
